[package]
name = "zmodem"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = []

[dependencies]
bitflags = { version = "*", features = ["bytemuck"] }
bytemuck = { version = "*", features = ["derive"] }
crc = "*"
