[package]
name = "chainload"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "*"
bytemuck = { version = "*", features = ["derive"] }
zmodem = { path = "../zmodem", default-features = false }
